Support 1.21.4
Nan1t/NanoLimbo pull request #104
Opened 2024-12-06 21:28 UTC by Quozul

This pull requests is based on the work from @BoomEaro in their pull request #98 

The PR #98 should be merged before this one.

2024-12-06 22:48 UTC, BoomEaro commented
Where did you find a fully prepared snbt codec file for 1.21.4? Because of this I had difficulties updating to 1.21.4 and I was going to send completely different registers to the client, as the vanilla client does

2024-12-06 23:24 UTC, Quozul commented
> Where did you find a fully prepared snbt codec file for 1.21.4? Because of this I had difficulties updating to 1.21.4 and I was going to send completely different registers to the client, as the vanilla server does

I did not find one, just hacked something in an hour until it works. This may be totally incomplete.

2024-12-06 23:49 UTC, BoomEaro requested changes

2024-12-06 23:49 UTC, BoomEaro commented on src/main/java/ua/nanit/limbo/protocol/packets/configuration/PacketPlayerLoaded.java
This packet is called ClientSettings and in this particular case there seems to be no point in decoding it

2024-12-07 08:50 UTC, Quozul commented on src/main/java/ua/nanit/limbo/protocol/packets/configuration/PacketPlayerLoaded.java
Where did you find the name of ClientSettings? Is there documentation available on this new packet?

2024-12-07 11:27 UTC, Potothingi commented
I'm looking forward to this becoming stable.

You can refer to the other Limbo github:
https://github.com/LOOHP/Limbo/commit/61331a3ea16f6bd732176723f3c9cc5b58ceb84b

2024-12-07 16:03 UTC, Quozul commented
It is going to take some time to rewrite all of this manually from the other Limbo...

2024-12-07 20:52 UTC, BoomEaro commented on src/main/java/ua/nanit/limbo/protocol/packets/configuration/PacketPlayerLoaded.java
Not long ago, the popular wiki for minecraft protocol - wiki.vg was closed, but the information is transferred to a new wiki here:
https://minecraft.wiki/w/Minecraft_Wiki:Projects/wiki.vg_merge/Protocol

The packet with the number 0x00 in the configuration phase of Serverbound is a ClientSettings packet, in addition to the fact that it has a locale field, your packet is missing 8 more fields.
And as I already said, decoding this packet is not required at all

2024-12-07 20:55 UTC, BoomEaro commented
If you don't mind, I can do the upgrade to 1.21.4 myself in my branch using a different approach and using different registers (without using snbt for the most part)

At this point all that is required to update to 1.21.4 is to update the mappings to 1.21.4 and the snbt codec. I am going to ditch the current codecs in favor of what the truly vanilla server sends to the client.

2024-12-07 21:09 UTC, Quozul commented
Sure, go ahead!

2024-12-09 17:39 UTC, closed without merging