Support 1.21.2
Nan1t/NanoLimbo pull request #98
Opened 2024-10-23 16:21 UTC by BoomEaro

Mojang changed the LoginSuccess and JoinGame packets, and the minecraft:ender_pearl element was added to the 1.21 damage_type codec for 1.21.2 clients.

2024-10-27 05:53 UTC, CyberFlameGO approved these changes

2024-12-05 18:13 UTC, Potothingi approved these changes

2024-12-06 21:34 UTC, Quozul commented
I created #104 to add support for 1.21.4 based on your work, thanks!

2024-12-09 01:29 UTC, BoomEaro commented
I updated to 1.21.4, but something might have broken on older versions. Let me know if something breaks

2024-12-09 04:39 UTC, Potothingi commented
1.21.1 - Network protocol error
1.20.6 - World background doesn't appear correctly as black.

2024-12-09 10:19 UTC, BoomEaro commented
> 1.21.1 - Network protocol error 1.20.6 - World background doesn't appear correctly as black.

Fixed 1.21.1. However, I can't reproduce the bug on 1.20.6. How does it look for you? Everything is correct for me.
Tested on vanilla

2024-12-09 15:44 UTC, Potothingi commented
1.21.1 - Network protocol error has been fixed.

1.20.6, 1.21.1 - Background still not black.

before:
![limbo_before](https://github.com/user-attachments/assets/4795f5a4-97d3-45ce-b8b8-9b1418330140)
this PR:
![limbo](https://github.com/user-attachments/assets/0124ac14-65de-4c8d-a8ae-d4afed2dd800)

2024-12-09 17:04 UTC, Potothingi requested changes
Shouldn't it be changed like this?
```
            if (version.moreOrEqual(Version.V1_21)) {
                msg.writeVarInt(dimensionRegistry.getDimension_1_21().getId());
            }
            else {
                msg.writeVarInt(dimensionRegistry.getDimension_1_20_5().getId());
            }
```

Applying this will fix the issue in 1.21.1, but will still cause issues in 1.20.5.

2024-12-09 17:06 UTC, Potothingi commented on src/main/java/ua/nanit/limbo/protocol/packets/play/PacketJoinGame.java
>              msg.writeVarInt(0);
^
`msg.writeVarInt(dimensionRegistry.getDimension_1_20_5().getId());`

2024-12-09 17:07 UTC, Potothingi commented on src/main/java/ua/nanit/limbo/protocol/packets/play/PacketJoinGame.java
>              msg.writeVarInt(0);
```
            if (version.moreOrEqual(Version.V1_21)) {
                msg.writeVarInt(dimensionRegistry.getDimension_1_21().getId());
            }
            else {
                msg.writeVarInt(dimensionRegistry.getDimension_1_20_5().getId());
            }
```

2024-12-09 17:15 UTC, Potothingi commented on src/main/java/ua/nanit/limbo/world/DimensionRegistry.java
>          dimension_1_20_5 = getModernDimension(def, codec_1_20);
```
dimension_1_20_5 = getModernDimension(def, codec_1_20_5);
```
After applying this, my issue with 1.20.5 was also resolved.

2024-12-09 20:39 UTC, BoomEaro commented
> 1.21.1 - Network protocol error has been fixed.
> 
> 1.20.6, 1.21.1 - Background still not black.
> 
> before: ![limbo_before](https://private-user-images.githubusercontent.com/108602622/393899169-4795f5a4-97d3-45ce-b8b8-9b1418330140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NzY4ODIsIm5iZiI6MTczMzc3NjU4MiwicGF0aCI6Ii8xMDg2MDI2MjIvMzkzODk5MTY5LTQ3OTVmNWE0LTk3ZDMtNDVjZS1iOGI4LTliMTQxODMzMDE0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQyMDM2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDRmYTFmNTJkMjBkM2VmMDY2MjcxYjNkZmE4Yjc1N2IwYjczOWRhMmRhNjc1NzlhZTQ0ZDRjZmNjY2EwN2I4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vsKPJnKM5Vn4oUoBeibDyTaD21HBc3u4SJ2EWm49U90) this PR: ![limbo](https://private-user-images.githubusercontent.com/108602622/393899176-0124ac14-65de-4c8d-a8ae-d4afed2dd800.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NzY4ODIsIm5iZiI6MTczMzc3NjU4MiwicGF0aCI6Ii8xMDg2MDI2MjIvMzkzODk5MTc2LTAxMjRhYzE0LTY1ZGUtNGM4ZC1hOGFlLWQ0YWZlZDJkZDgwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQyMDM2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzYxNzY2NmQ1NmYwNDcwYjgzMjljOGM4ZTAzYzkzMTI3ZDBiYWIyMzA0NTBkMTk0M2QyZDhlZGQ3MTMwM2RmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5N5fS6rQ1RS1SO0qQnJhJWgEX-aqI6pBGIB2_ti5PNw)

Ohh, looks like I messed up the dimension IDs. In your screenshot it's the_nether.
I will check

2024-12-09 22:07 UTC, BoomEaro commented on src/main/java/ua/nanit/limbo/world/DimensionRegistry.java
>          dimension_1_20_5 = getModernDimension(def, codec_1_20);
Thanks!

2024-12-09 22:09 UTC, BoomEaro commented on src/main/java/ua/nanit/limbo/protocol/packets/play/PacketJoinGame.java
>              msg.writeVarInt(0);
Codec 1.20.5 and 1.21 use the same dimension numbers, so this is not required

2024-12-10 09:36 UTC, Pantera07 approved these changes

2024-12-10 09:37 UTC, Potothingi approved these changes

2025-01-11 05:51 UTC, CyberFlameGO approved these changes
LGTM

2025-01-11 15:30 UTC, mzrtamp approved these changes

2025-02-11 02:39 UTC, AkselGlyholt commented
I tried testing this, and I still cannot connect when using 1.21.4?

2025-02-11 11:59 UTC, BoomEaro commented
> I tried testing this, and I still cannot connect when using 1.21.4?

How exactly are you trying to connect and what is the kick message when connecting to nanolimbo?

2025-02-11 12:21 UTC, AkselGlyholt commented
Connecting with a Vanilla client on 1.21.4 and it's telling me that it's an unsupported client version

2025-02-11 12:36 UTC, BoomEaro commented
> Connecting with a Vanilla client on 1.21.4 and it's telling me that it's an unsupported client version

Try to download this version: https://github.com/BoomEaro/NanoLimbo/releases/tag/1.21.4-fix

2025-02-11 14:08 UTC, AkselGlyholt commented
Oh, I must've downloaded the wrong version then? Works perfectly fine now.

2025-03-25 16:30 UTC, Potothingi commented
1.21.5 has been released, NanoLimbo does not currently appear to be compatible with this version.
https://github.com/Nan1t/NanoLimbo/issues/105

2025-03-25 22:53 UTC, BoomEaro commented
> 1.21.5 has been released, NanoLimbo does not currently appear to be compatible with this version. #105

Tried to add support for 1.21.5. Let me know if something is wrong

2025-03-26 06:53 UTC, Pantera07 approved these changes

2025-03-28 07:07 UTC, Pantera07 commented
After the 'Support 1.21.5' commit, TabComplete does not work on clients from 1.20.5 to 1.21.4. (Tested on Velocity)

2025-03-28 07:47 UTC, Pantera07 requested changes

2025-03-28 07:47 UTC, Pantera07 commented on src/main/java/ua/nanit/limbo/protocol/registry/State.java
> +                    map(0x10, V1_20_5, V1_21_5)
`map(0x10, V1_20_5, V1_21_5)` -> `map(0x10, V1_21_5, V1_21_5)`

2025-03-28 11:52 UTC, BoomEaro commented on src/main/java/ua/nanit/limbo/protocol/registry/State.java
> +                    map(0x10, V1_20_5, V1_21_5)
Thanks!

2025-04-05 17:37 UTC, BoomEaro commented
I have completely reworked the registry sending for all versions of the game and also added the necessary decoding checks in some packets. These changes should maximize the compatibility and security of nanolimbo.

Let me know if I broke something.

2025-04-06 15:11 UTC, jonesdevelopment approved these changes

2025-04-06 15:12 UTC, jonesdevelopment commented
I'm closing #95 and #94 as they are replaced by this.

2025-04-16 11:38 UTC, pierrelasse commented
Any ETA for when this is done?

2025-04-16 12:35 UTC, BoomEaro commented
> Any ETA for when this is done?

This pull request is ready. You can download the compiled jar here: https://github.com/BoomEaro/NanoLimbo/releases/tag/1.21.5_1.9_1

2025-04-18 07:52 UTC, TheFaerMan commented
> > Есть ли какие-нибудь расчетные сроки завершения?
> 
> Этот запрос на извлечение готов. Вы можете скачать скомпилированный jar здесь: https://github.com/BoomEaro/NanoLimbo/releases/tag/1.21.5_1.9_1

![image](https://github.com/user-attachments/assets/01d580fb-8133-4c49-8799-a3b524bd9a3c)

2025-04-19 00:12 UTC, TubYoub commented
> > Any ETA for when this is done?
> 
> This pull request is ready. You can download the compiled jar here: https://github.com/BoomEaro/NanoLimbo/releases/tag/1.21.5_1.9_1

Is this release working for anyone? Because for me the server refuses connection from any Minecraft Version. Maybe its anything in my setup or its an issue with the Plugin idk.

2025-04-19 00:29 UTC, BoomEaro commented
> Is this release working for anyone? Because for me the server refuses connection from any Minecraft Version. Maybe its anything in my setup or its an issue with the Plugin idk.
Make sure you have configured the port and ip address correctly

2025-04-19 01:36 UTC, TubYoub commented
> Make sure you have configured the port and ip address correctly

I reinstalled the server and just copied the settings over. and that new servewr had a diff port... now thats awkward.....
**this never happened**

2025-06-18 10:41 UTC, Potothingi commented
Could you please update to support 1.21.6?

2025-06-18 19:57 UTC, BoomEaro commented
Added support for 1.21.6 and updated dependencies. Let me know if something is wrong

2025-06-19 07:23 UTC, Pantera07 approved these changes

2025-06-21 11:56 UTC, TheFaerMan commented
Please tell me where I can download for 1.21.6?

2025-06-21 15:49 UTC, BoomEaro commented
> Please tell me where I can download for 1.21.6?

You can download here: https://github.com/BoomEaro/NanoLimbo/releases/tag/1.9.4

2025-07-03 07:49 UTC, OoLunar commented
I have a bit of a feature request that doesn't necessarily align with the project's minimalist principles but might be small enough to squeeze in:

![image](https://github.com/user-attachments/assets/6bbf5f84-1611-40fe-b257-a4cabd50c6cb)

I'm wanting to make an Undertale reference through the player list. Could we add a config setting to the `playerList` section that allows for us to set the player's skin?

---

Unrelated, could we also get #89 merged? Either as another config setting or as a direct merge. 

---

Thank you for this PR!! I'm extremely thankful since the other Limbo project was using 44% of my CPU just idling without players:

![image](https://github.com/user-attachments/assets/76cc490c-05e9-47d4-a259-b32be2a693b5)

While your project is better in nearly every single way:

![image](https://github.com/user-attachments/assets/16d6e5db-6bbc-421a-9d84-aff71aa7d480)

2025-07-05 13:11 UTC, BoomEaro commented
I applied the following pull requests:
https://github.com/Nan1t/NanoLimbo/pull/89
https://github.com/Nan1t/NanoLimbo/pull/93

According to my tests, everything seems to work correctly

2025-07-05 13:16 UTC, BoomEaro commented
> I have a bit of a feature request that doesn't necessarily align with the project's minimalist principles but might be small enough to squeeze in:
> 
> ![image](https://private-user-images.githubusercontent.com/46751150/461903049-6bbf5f84-1611-40fe-b257-a4cabd50c6cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTE3MjEyNTMsIm5iZiI6MTc1MTcyMDk1MywicGF0aCI6Ii80Njc1MTE1MC80NjE5MDMwNDktNmJiZjVmODQtMTYxMS00MGZlLWIyNTctYTRjYWJkNTBjNmNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzA1VDEzMDkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlOTNjMDUxOWRiNTQ5ODM5MTQ0NDA1NmNjNjI0ZWY4MWI2YWYzNDE1YTU5NzEwODlmODQ4MGE2ZDBmM2EyZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Oo1F-cF97Htemylvsjwx2o3_rznr7J5ckbhNlqrOZkc)
> 
> I'm wanting to make an Undertale reference through the player list. Could we add a config setting to the `playerList` section that allows for us to set the player's skin?

Maybe in the future when I have more time I can try to implement this feature

2025-08-10 16:19 UTC, Pantera07 commented
I added a BPS check to the Packet Limiter.
https://github.com/BoomEaro/NanoLimbo/pull/3

2026-04-14 15:14 UTC, merged